// <auto-generated />
namespace Tuffab.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class QuoteRequestSubmit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuoteRequestSubmit));
        
        string IMigrationMetadata.Id
        {
            get { return "201602090433531_QuoteRequestSubmit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
